<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\Jugador\" />
    <Folder Include="Mappings\" />
    <Folder Include="NewFolder\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
